### Support Vector Machine

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import missingno as msno

In [2]:
def NormalizeData(data):
    return (data - np.min(data)) / (np.max(data) - np.min(data))

In [19]:
# Loading the dataset
train = pd.read_csv("../data/setB_train.psv", sep='|')
test = pd.read_csv("../data/setB_test.psv", sep='|')

# Visualize missing values as a matrix
#msno.matrix(train)
#msno.matrix(test)
#msno.matrix(pd.read_csv("../data/setB_train.psv", sep='|'))
#msno.matrix(pd.read_csv("../data/setB_test.psv", sep='|'))

In [20]:
#msno.bar(train)

In [21]:
#msno.bar(test)

In [22]:
train = pd.read_csv("../data/setA_train.psv", sep='|')
#print(train.shape)
#print(train)
#drop columns which have more than 94% NaN's by index
#cols = [7,14,16,20,22,26,27,32]
cols = [7,20,27]
train.HospAdmTime = -1 * train.HospAdmTime
train=train.drop(train.columns[cols],axis=1)
#replace NaN with mean
train[np.isnan(train)] = -99
#train=train.fillna(train.mean())

train=train.values
test = pd.read_csv("../data/setA_test.psv", sep='|')
#train, test = train_test_split(train, test_size=0.2)
#print(train.shape)
#print(train)
test.HospAdmTime = -1 * test.HospAdmTime
test=test.drop(test.columns[cols],axis=1)
#replace NaN with mean
test[np.isnan(test)] = -99
#test=test.fillna(test.mean())
test=test.values
 
#train, test = train_test_split(train, test_size=0.2)
#print(train.shape)
#print(train)

In [23]:
x_train_raw = train[:, :-1] # for all but last column
n_rows, n_cols = x_train_raw.shape

x_test_raw = test[:, :-1]
y_train = train[:, -1]  # for last column
y_test = test[:, -1]  # for last column
x_train = NormalizeData(x_train_raw)
x_test = NormalizeData(x_test_raw)
#x_train = x_train_raw
#x_test = x_test_raw
print(x_test)
print(y_test)

[[0.02522051 0.02673649 0.         ... 0.         0.01364802 0.01998346]
 [0.02742558 0.02556505 0.         ... 0.         0.01364802 0.02039691]
 [0.02852811 0.02687431 0.         ... 0.01364388 0.01365077 0.01943219]
 ...
 [0.03293826 0.02701213 0.         ... 0.         0.01364802 0.01819184]
 [0.03018192 0.02687431 0.         ... 0.         0.01364802 0.01832966]
 [0.02949283 0.02673649 0.         ... 0.         0.01364802 0.01846748]]
[0. 0. 0. ... 1. 1. 1.]


In [24]:
from sklearn.svm import SVC
#svclassifier = SVC(kernel='linear', probability=True) # in default probability=false; proba data will be used for ROC AUC
#svclassifier = SVC(kernel='linear') # in default probability=false; use it to save run time!
svclassifier = SVC(kernel='rbf', C=2) # Gaussian kernel
#svclassifier = SVC(kernel='poly', degree=2)
svclassifier.fit(x_train, y_train)

SVC(C=2, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [25]:
y_pred = svclassifier.predict(x_test)
#y_proba = svclassifier.predict_proba(x_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred, labels=[1, 0]))
print(classification_report(y_test,y_pred))
#print(y_test)

[[2294 1056]
 [ 450 7274]]
              precision    recall  f1-score   support

         0.0       0.87      0.94      0.91      7724
         1.0       0.84      0.68      0.75      3350

    accuracy                           0.86     11074
   macro avg       0.85      0.81      0.83     11074
weighted avg       0.86      0.86      0.86     11074



In [26]:
#np.set_printoptions(threshold=np.inf)
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix

In [27]:
#print(y_proba[:5])
#y_probs = y_proba[:,0]
#y_probs[:5]

In [28]:
#y_probs = y_proba[:,0]
y_classes = y_pred
# accuracy: (tp + tn) / (p + n)
accuracy = accuracy_score(y_test, y_classes)
print('Accuracy: %f' % accuracy)
# precision tp / (tp + fp)
precision = precision_score(y_test, y_classes)
print('Precision: %f' % precision)
# recall: tp / (tp + fn)
recall = recall_score(y_test, y_classes)
print('Recall: %f' % recall)
# f1: 2 tp / (2 tp + fp + fn)
f1 = f1_score(y_test, y_classes)
print('F1 score: %f' % f1)
# kappa
kappa = cohen_kappa_score(y_test, y_classes)
print('Cohens kappa: %f' % kappa)
# ROC AUC
#auc = roc_auc_score(y_test, y_probs)
#print('ROC AUC: %f' % auc)
# confusion matrix
print('Confusion_matrix:')
print('                    TrueP FalseN')
print('                    FalseP TrueN')
#labels must be specified as [1,0]. Without it, confusion_matrix
#will report negative on the 1st row then positives on the 2nd row
#note: predictions are in columns and actual values in rows !!
matrix = confusion_matrix(y_test, y_classes, labels=[1, 0])
print(matrix)

Accuracy: 0.864006
Precision: 0.836006
Recall: 0.684776
F1 score: 0.752872
Cohens kappa: 0.660338
Confusion_matrix:
                    TrueP FalseN
                    FalseP TrueN
[[2294 1056]
 [ 450 7274]]
